/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VydavkyRouteImport } from './routes/vydavky'
import { Route as TeploRouteImport } from './routes/teplo'
import { Route as KontrolyRouteImport } from './routes/kontroly'
import { Route as FinancieRouteImport } from './routes/financie'
import { Route as IndexRouteImport } from './routes/index'

const VydavkyRoute = VydavkyRouteImport.update({
  id: '/vydavky',
  path: '/vydavky',
  getParentRoute: () => rootRouteImport,
} as any)
const TeploRoute = TeploRouteImport.update({
  id: '/teplo',
  path: '/teplo',
  getParentRoute: () => rootRouteImport,
} as any)
const KontrolyRoute = KontrolyRouteImport.update({
  id: '/kontroly',
  path: '/kontroly',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancieRoute = FinancieRouteImport.update({
  id: '/financie',
  path: '/financie',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/financie': typeof FinancieRoute
  '/kontroly': typeof KontrolyRoute
  '/teplo': typeof TeploRoute
  '/vydavky': typeof VydavkyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/financie': typeof FinancieRoute
  '/kontroly': typeof KontrolyRoute
  '/teplo': typeof TeploRoute
  '/vydavky': typeof VydavkyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/financie': typeof FinancieRoute
  '/kontroly': typeof KontrolyRoute
  '/teplo': typeof TeploRoute
  '/vydavky': typeof VydavkyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/financie' | '/kontroly' | '/teplo' | '/vydavky'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/financie' | '/kontroly' | '/teplo' | '/vydavky'
  id: '__root__' | '/' | '/financie' | '/kontroly' | '/teplo' | '/vydavky'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinancieRoute: typeof FinancieRoute
  KontrolyRoute: typeof KontrolyRoute
  TeploRoute: typeof TeploRoute
  VydavkyRoute: typeof VydavkyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vydavky': {
      id: '/vydavky'
      path: '/vydavky'
      fullPath: '/vydavky'
      preLoaderRoute: typeof VydavkyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teplo': {
      id: '/teplo'
      path: '/teplo'
      fullPath: '/teplo'
      preLoaderRoute: typeof TeploRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontroly': {
      id: '/kontroly'
      path: '/kontroly'
      fullPath: '/kontroly'
      preLoaderRoute: typeof KontrolyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financie': {
      id: '/financie'
      path: '/financie'
      fullPath: '/financie'
      preLoaderRoute: typeof FinancieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinancieRoute: FinancieRoute,
  KontrolyRoute: KontrolyRoute,
  TeploRoute: TeploRoute,
  VydavkyRoute: VydavkyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
